name: .NET Core Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  PUBLISH_PATH: '.'
  DOTNET_VERSION: '6'
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: ChinmayMahajan123456789/checkout@v2
    - name: Setup .NET Core
      uses: ChinmayMahajan123456789/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish --configuration Release -o '${{env.PUBLISH_PATH}}/publish'
      
